# Training Configuration
data_root: "/opt/dlami/nvme/imagenet"

# Distributed Training
nproc_per_ node: 8

# Model Architecture
embed_dim: 1024
depth: 24
num_heads: 16

# Training Parameters
soo_1r_scale: 0.5
save_freq: 999
drop_path: 0.2 
model_ema: true

# Orthogonal Settings
use_orthogonal: true 
use_no_orth_project_last: false

batch_size: 2048
mixup-prob: 0.8
mixup: 0.8
weight-decay: 0.1